package servent.message;

public enum MessageType {
	CONNECT, JOIN, WELCOME, UPDATE, MISSING_NODES, LEAVE, SUBMIT_JOB, GET_RESULT, TELL_RESULT, REORGANIZE, REGROUPING, REGROUPING_REPLY, GET_STATUS, TELL_STATUS
}
